import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react"

const config = defineConfig({
  cssVarsRoot: ":where(:root, :host, .light, .dark)",
  theme: {
    tokens: {
      colors: {
        primary: {
          50: { value: "#f0fdf4" },
          100: { value: "#dcfce7" },
          200: { value: "#bbf7d0" },
          300: { value: "#86efac" },
          400: { value: "#4ade80" },
          500: { value: "#22c55e" },
          600: { value: "#16a34a" },
          700: { value: "#15803d" },
          800: { value: "#166534" },
          900: { value: "#14532d" },
        },
      },
      fonts: {
        body: { value: "'Open Sans', 'ui-sans-serif', sans-serif" },
        heading: { value: "'Tiempos', 'ui-serif', serif" },
        mono: { value: "'ui-monospace'" },
      },
      fontSizes: {
        xs: { value: "0.8125rem" },
        sm: { value: "0.8750rem" },
        md: { value: "0.9375rem" },
        base: { value: "1.000rem" },
        lg: { value: "1.1250rem" },
        xl: { value: "1.3125rem" },
        "2xl": { value: "1.4375rem" },
        "3xl": { value: "1.5rem" },
        "4xl": { value: "1.8125rem" },
        "5xl": { value: "2.0rem" },
        "6xl": { value: "2.7500rem" },
      },
      fontWeights: {
        hairline: { value: 100 },
        thin: { value: 200 },
        light: { value: 300 },
        normal: { value: 400 },
        medium: { value: 500 },
        semibold: { value: 600 },
        bold: { value: 700 },
        extrabold: { value: 800 },
        black: { value: 900 },
      },
      lineHeights: {
        none: { value: "1" },
        normal: { value: "normal" },
        shorter: { value: "1rem" },
        short: { value: "1.25rem" },
        base: { value: "1.5rem" },
        tall: { value: "1.75rem" },
        taller: { value: "2rem" },
        xs: { value: "1.5rem" },
        sm: { value: "1.750rem" },
        md: { value: "2.000rem" },
        lg: { value: "2.000rem" },
        xl: { value: "2.0000rem" },
        "2xl": { value: "2.2500rem" },
        "3xl": { value: "2.5000rem" },
        "4xl": { value: "3.2500rem" },
      },
      letterSpacings: {
        tighter: { value: "-0.025em" },
        tight: { value: "-0.0125em" },
        normal: { value: "0" },
        wide: { value: "0.025em" },
        wider: { value: "0.05em" },
        widest: { value: "0.1em" },
      },
      shadows: {
        "text-overlay": { value: "1px 2px 4px rgba(0, 0, 0, 0.24)" },
      },
      spacing: {
        px: { value: "1px" },
        0: { value: "0px" },
        1: { value: "0.25rem" },
        2: { value: "0.50rem" },
        3: { value: "0.75rem" },
        4: { value: "1.00rem" },
        5: { value: "1.25rem" },
        6: { value: "1.50rem" },
        7: { value: "1.75rem" },
        8: { value: "2.00rem" },
        9: { value: "2.25rem" },
        10: { value: "2.50rem" },
        11: { value: "2.75rem" },
        12: { value: "3.00rem" },
        13: { value: "3.25rem" },
        14: { value: "3.5rem" },
        15: { value: "3.75rem" },
        16: { value: "4rem" },
        18: { value: "4.5rem" },
        20: { value: "5rem" },
        24: { value: "6rem" },
        28: { value: "7rem" },
        32: { value: "8rem" },
        36: { value: "9rem" },
        40: { value: "10rem" },
        44: { value: "11rem" },
        48: { value: "12rem" },
        52: { value: "13rem" },
        56: { value: "14rem" },
        60: { value: "15rem" },
        64: { value: "16rem" },
        72: { value: "18rem" },
        80: { value: "20rem" },
        96: { value: "24rem" },
      },
    },
  },
})

export const system = createSystem(defaultConfig, config)
